---
- name: Get mountpoint
  shell:
    cmd: "findmnt -mlno TARGET --target {{ item.dir }}"
  register: findmnt
  changed_when: false
- name: Setup fscrypt
  shell:
    cmd: fscrypt setup --all-users --quiet {{ findmnt.stdout }}
  ignore_errors: true
- name: Encrypt directory
  shell:
    # FIXME: the name might fail if dir is just /
    cmd: "echo '{{ item.password }}' | fscrypt encrypt --quiet --user={{ item.user }} --source=custom_passphrase --name {{ item.dir }} --skip-unlock {{ item.dir }}"
  register: encrypted
  changed_when: false
  ignore_errors: true
