---
- name: Install dependencies
  package:
    name: git
    state: present
- name: Install fscrypt from source
  include_tasks:
    file: install_from_source.yml
      #- name: Setup fscrypt on mountpoint ({{ item }})
      #  include_tasks:
      #    file: "{{ encrypt_directory }}"
      #  loop: fscrypt_filesystems
      #  when: fscrypt_force_filesystem_setup == true
- name: Create encryption on directory
  include_tasks:
    file: encrypt_directory.yml
  loop: "{{ fscrypt_encrypt_directories }}"
  when: fscrypt_encrypt_directories | length > 0
- name: Unlock directory ({{ item }})
  include_tasks:
    file: unlock_directory.yml
  loop: "{{ fscrypt_unlock_directories }}"
  when: fscrypt_unlock_directories | length > 0
